disabled_rules:
  - force_cast
  - force_try
  - variable_name
  - shorthand_operator

excluded:
  - Pods
  - web3swift-macOS_Tests
  - web3swiftTests

type_body_length:
  - 300 # warning
  - 500 # error

function_parameter_count: 8

line_length: 140
